# Generated by Django 3.0.4 on 2020-03-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='currently_logged_in',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='access_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='loggedin',
            field=models.BooleanField(default=False),
        ),
    ]
